In [2]:
import numpy as np

### Different Ways of Creating Numpy Array
**numpy.array()**: Numpy array object in Numpy is called ndarray. We can create ndarray using this function.

`Syntax: numpy.array(parameter)`

In [3]:
ary = [[1, 2], [3, 4]]

arr1 = np.array([1, 2, 3])
arr2 = np.array(ary)

print("Numpy Array 1:\n", arr1)
print("Numpy Array 2:\n", arr2)

Numpy Array 1:
 [1 2 3]
Numpy Array 2:
 [[1 2]
 [3 4]]


In [4]:
list_1 = [1, 2, 3, 4]
list_2 = [5, 6, 7, 8]
list_3 = [9, 10, 11, 12]

sample_array = np.array([list_1, 
                         list_2,
                         list_3])
print("Numpy multi dimensional array in python\n",
      sample_array)

Numpy multi dimensional array in python
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


**numpy.fromiter()**: The fromiter() function create a new one-dimensional array from an iterable object.

`Syntax: numpy.fromiter(iterable, dtype, count=-1)`

In [5]:
var = "HelloWorld!"

arr = np.fromiter(var, dtype = 'U2')

print("fromiter() array :",
      arr)

fromiter() array : ['H' 'e' 'l' 'l' 'o' 'W' 'o' 'r' 'l' 'd' '!']


**numpy.empty()**: This function create a new array of given shape and type without initializing value.

`Syntax: numpy.empty(shape, dtype=float, order='C')`

In [ ]:
np.empty([4, 3], dtype = np.int32)

array([[   4128768,    6619251,         82],
       [   6029375,    7536754,    3211264],
       [-348705910,    5570652,          0],
       [   5570652,    4522067,     786432]])

In [ ]:
zeros_arr = np.zeros((2, 3)) # Creates an array of zeros
ones_arr = np.ones((2, 2))   # Creates an array of ones
range_arr = np.arange(0, 10, 2) # Creates an array with a range of values

print("Array of Zeros:\n", zeros_arr)
print("\n Array of Ones:\n", ones_arr)
print("\n Array with Range of Values:\n", range_arr)

**Indexing and Slicing:**
- Access elements using square brackets, similar to Python lists.
- Supports multi-dimensional indexing and slicing for extracting sub-arrays.

In [23]:
my_array = np.array([[1, 2, 3], [4, 5, 6]])
element = my_array[0, 1] # Accesses element at row 0, column 1 (value 2)
subset = my_array[:, 1:] # Slices all rows, columns from index 1 onwards

print("Accessed Element:", element)
print("Sliced Sub-array:\n", subset)

Accessed Element: 2
Sliced Sub-array:
 [[2 3]
 [5 6]]


In [24]:
a = np.array([10, 20, 30, 40, 50])

In [25]:
# Single index
print(a[0])   # 10
print(a[3])   # 40

# Negative index
print(a[-1])  # 50
print(a[-2])  # 40

10
40
50
40


In [ ]:
# Basic Slicing (1D Array)
# Format: a[start:end:step]

print(a[1:4])       # [20, 30, 40]
print(a[:3])        # [10, 20, 30]
print(a[2:])        # [30, 40, 50]
print(a[::2])       # [10, 30, 50]   (step 2)
print(a[::-1])      # [50, 40, 30, 20, 10] (reverse)

In [ ]:
# Indexing in 2D Arrays

In [ ]:
b = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])


In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
result_sum = a + b
result_mult = a * 2

In NumPy, **`order='C'`** and **`order='F'`** define **how data is stored in memory** and **how arrays are flattened or reshaped**.

#### **1. Meaning of C-order and F-order**

**C-order (Row-major order)**

* Stores data **row by row**, like C programming.
* Last axis changes fastest.
* Reads rows contiguously in memory.

**F-order (Column-major order)**

* Stores data **column by column**, like Fortran/Matlab.
* First axis changes fastest.
* Reads columns contiguously in memory.


#### ✅ **When Does It Matter?**

**Use C-order when:**

* General numerical code
* Python/C libraries
* Deep learning tensors (PyTorch)

**Use F-order when:**

* Interacting with Fortran/Matlab
* Linear algebra (BLAS/LAPACK operate faster sometimes)
* Column-major optimizations

### **Flattening Example**

#### ➤ **C-order flattening**

In [17]:
a = np.array([[1, 2],[3, 4]])
a.flatten(order='C')

array([1, 2, 3, 4])

In [18]:
a = np.array([[1, 2],[3, 4]])
a.reshape((2,2), order='C')


array([[1, 2],
       [3, 4]])

#### ➤ **F-order flattening**

In [19]:
a = np.array([[1, 2],[3, 4]])
a.flatten(order='F')

array([1, 3, 2, 4])

In [21]:
a = np.array([[1, 2],[3, 4]])
a.reshape((2,2), order='F')


array([[1, 2],
       [3, 4]])