In [1]:
import torch
import numpy as np
import random

`torch.manual_seed()`, `np.random.seed()`, and `random.seed()` — what they do, what happens with and without seeds, and simple code examples you can run to understand the concept deeply.

---

## 🔥 **What Is a Seed?**

Whenever you generate random numbers (for ML, sampling, splitting datasets, initializing weights), computers use a **pseudo-random number generator (PRNG)**.

A **seed** is the *starting point* for this PRNG.
If you use the **same seed**, you get **the same sequence of "random" numbers** every time — which makes experiments **reproducible**.

---

## ✅ **Why Do We Use Seeds?**

#### ✔ To reproduce model results exactly

Same model + same data + same seed = same outputs.

#### ✔ For debugging

You can test multiple things while keeping randomness fixed.

#### ✔ For teaching / tutorials

Everyone sees the exact same numbers.

---

## ❌ **What Happens If You Don’t Use a Seed?**

* Each run generates **different random numbers**.
* Weight initialization changes → model performance varies.
* Train/validation splits change.
* Sampling / augmentations differ.
* Harder to debug because every run is different.

---

## 🌱 **What Happens When You Use a Seed?**

* Random numbers become **predictable** and **repeatable**.
* Same code → same output, every run.

---

## 📌 Three Types of Seeds You Encounter

### 1️⃣ **PyTorch** → `torch.manual_seed()`

Controls randomness in:

* torch.rand()
* weight initialization in nn.Module
* dropout randomness
* some CUDA operations (if you also set cuda seeds)

Example:

```python
import torch

torch.manual_seed(42)
print(torch.randn(3))
```

---

### 2️⃣ **NumPy** → `np.random.seed()`

Controls randomness in:

* np.random.rand()
* np.random.randint()
* NumPy-based dataset shuffling

Example:

```python
import numpy as np

np.random.seed(42)
print(np.random.rand(3))
```

---

### 3️⃣ **Python’s built-in random** → `random.seed()`

Controls randomness in:

* random.random()
* random.shuffle()
* random.choice()

Example:

```python
import random

random.seed(42)
print(random.random())
```

---

## 🧪 **Now Let's See Effects With & Without Seeds**

---

### 🔬 **A. PyTorch Example**

#### ❌ Without Seed → Different results

```python
import torch

print(torch.randn(3))
print(torch.randn(3))
```

Running twice → different outputs each time:

```
tensor([ 0.34, -1.23,  0.89])
tensor([-0.56,  0.44,  1.03])
```

---

#### ✔ With Seed → Same results every time

```python
import torch

torch.manual_seed(0)
print(torch.randn(3))

torch.manual_seed(0)
print(torch.randn(3))
```

Both prints are identical:

```
tensor([ 1.5410, -0.2934, -2.1788])
tensor([ 1.5410, -0.2934, -2.1788])
```

---

### 🔬 **B. NumPy Example**

#### ❌ Without Seed

```python
import numpy as np
print(np.random.rand(3))
print(np.random.rand(3))
```

Different values each run.
```
[0.04170374 0.4521037  0.88870225]
[0.59730074 0.04363884 0.14128526]
```

#### ✔ With Seed

```python
np.random.seed(10)
print(np.random.rand(3))
np.random.seed(10)
print(np.random.rand(3))
```

Same values every time.
```
[0.77132064 0.02075195 0.63364823]
[0.77132064 0.02075195 0.63364823]
```

---

### 🔬 **C. Python Random Example**

#### ❌ Without Seed

```python
import random
print(random.randint(1, 100))
print(random.randint(1, 100))
```
Different values each run.
```
37
74
```

#### ✔ With Seed

```python
random.seed(10)
print(random.randint(1, 100))
random.seed(10)
print(random.randint(1, 100))
```

Repeatable output.
```
22
22
```

---

## ⚠ Important Note

**Setting torch seed does NOT affect numpy or python random.**
They are **separate random generators**.

For complete reproducibility:

```python
import torch, numpy as np, random

seed = 42

torch.manual_seed(seed)
np.random.seed(seed)
random.seed(seed)
```

---

## 🧩 Mini Playground: Compare All Three

In [8]:
print("\n--- Without seed ---")
print("torch:", torch.randn(2))
print("numpy:", np.random.rand(2))
print("random:", random.random())

# Repeat to show difference
print("torch:", torch.randn(2))
print("numpy:", np.random.rand(2))
print("random:", random.random())

print("\n--- With seed = 123 ---")
torch.manual_seed(123)
np.random.seed(123)
random.seed(123)

print("torch:", torch.randn(2))
print("numpy:", np.random.rand(2))
print("random:", random.random())

# Repeat to show SAME numbers
torch.manual_seed(123)
np.random.seed(123)
random.seed(123)

print("torch:", torch.randn(2))
print("numpy:", np.random.rand(2))
print("random:", random.random())


--- Without seed ---
torch: tensor([ 2.0509, -1.1452])
numpy: [0.74880388 0.49850701]
random: 0.032585065282054626
torch: tensor([-0.6911,  0.9285])
numpy: [0.22479665 0.19806286]
random: 0.48256167455085586

--- With seed = 123 ---
torch: tensor([-0.1115,  0.1204])
numpy: [0.69646919 0.28613933]
random: 0.052363598850944326
torch: tensor([-0.1115,  0.1204])
numpy: [0.69646919 0.28613933]
random: 0.052363598850944326


## 🧠 Final Summary (Easy Memorable Points)

#### **1. Seeds freeze randomness.**

Same seed → same results.

#### **2. Each library has its own seed.**

* PyTorch → `torch.manual_seed()`
* NumPy → `np.random.seed()`
* Python → `random.seed()`

#### **3. Without seeds → every run differs.**

74
74


## Question:
```
Below given code I applied torch seed, but second and third print didn't give same results like first print, why so?

torch.manual_seed(3)
print(torch.randn(3))
print(torch.randn(3))
print(torch.randn(3))
````


## ✅ **Why second and third prints are different even after torch.manual_seed()?**

Because:

#### 👉 **`torch.manual_seed(3)` only sets the seed *once*, at that moment.**

After that, every call to `torch.randn()` continues the random sequence.

It does **NOT** restart the sequence for every new `print()`
unless you **set the seed again**.

---

## 🔍 Example Breakdown

Your code:

```python
torch.manual_seed(3)
print(torch.randn(3))   # Output A
print(torch.randn(3))   # Output B (next numbers in sequence)
print(torch.randn(3))   # Output C (next numbers in sequence)
```

Here’s what happens internally:

1. You set seed → random sequence starts from fixed point.
2. First `randn` → uses values 1,2,3 from the sequence.
3. Second `randn` → uses values 4,5,6 from the same sequence.
4. Third `randn` → uses values 7,8,9.

So **they are different outputs — but they are consistently reproducible each run.**

Run the above code 10 times → all 10 will produce the *same three different rows*.

---

## 🧪 If you want the SAME output each time, you must reset the seed:

```python
torch.manual_seed(3)
print(torch.randn(3))

torch.manual_seed(3)
print(torch.randn(3))

torch.manual_seed(3)
print(torch.randn(3))
```

Now all three outputs will match.

---

## ✔ Why does this work?

Each time you call `torch.manual_seed(3)`, you restart the PRNG at the same point, so `torch.randn(3)` always gives the same numbers.

---

## 🎯 Summary (Super Clear)

#### ❌ One seed → different outputs

```
seed → rand → next rand → next rand
```

#### ✔ Reset seed before each call → same output

```
seed → rand
seed → rand
seed → rand
```

