In [1]:
import torch
import numpy as np

In [2]:
arr = np.array([1, 2, 3])

tensor = torch.tensor(arr)

print(tensor)

tensor([1, 2, 3], dtype=torch.int32)


In [3]:
arr = np.array([[1, 2, 3],[4,5,6]])

tensor = torch.tensor(arr)

print(tensor)

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)


In [4]:
tensor = torch.zeros((3,4))
print(tensor)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [5]:
tensor = torch.ones((3,4))
print(tensor)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [6]:
# default dtype is float32
tensor = torch.zeros((3,4),dtype=torch.float16)
print(tensor, tensor.dtype)

# we can also manually set the dtype
tensor = torch.zeros((3,4), dtype=torch.float16)
print(tensor)
tensor = torch.ones((3,4), dtype=torch.int32)
print(tensor)
tensor = torch.rand((3,4), dtype = torch.double)
print(tensor)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]], dtype=torch.float16) torch.float16
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]], dtype=torch.float16)
tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]], dtype=torch.int32)
tensor([[0.2108, 0.5876, 0.9157, 0.7846],
        [0.8629, 0.8118, 0.6189, 0.0231],
        [0.6050, 0.9401, 0.4860, 0.5094]], dtype=torch.float64)


### Shape, Size, and Reshaping

In [7]:
a = torch.rand(2, 3)

# Shape
print(a.shape)          # torch.Size([2, 3])
print(a.size())         # same

# Number of elements
print(a.numel())        # 6

# Reshape
print(a.view(3, 2))
print(a.reshape(3, 2))  # safer than view

# Add new dimension
print(a.unsqueeze(0).shape)   # (1, 2, 3)
print(a.unsqueeze(1).shape)   # (2, 1, 3)

# Remove dimension
b = a.unsqueeze(0)         # shape (1, 2, 3)
print(b.squeeze().shape)   # (2, 3)


torch.Size([2, 3])
torch.Size([2, 3])
6
tensor([[0.5881, 0.8420],
        [0.8792, 0.6873],
        [0.2656, 0.0879]])
tensor([[0.5881, 0.8420],
        [0.8792, 0.6873],
        [0.2656, 0.0879]])
torch.Size([1, 2, 3])
torch.Size([2, 1, 3])
torch.Size([2, 3])


### Basic Math Operations

In [8]:
a = torch.rand(2, 3)
b = torch.ones(2, 3)

# Addition
c = a + b
c = torch.add(a, b)

# Subtraction
d = a - b
d = torch.sub(a, b)

# Multiplication (element wise)
e = a * b
e = torch.mul(a, b)

# Division
f = a / b
f = torch.div(a, b)

# Power
p = a ** 2
p = torch.pow(a, 2)


### In-place Operations (modifies tensor)

All in-place functions end with `_`.

⚠ In-place ops modify data that may be required for autograd—use carefully.

In [9]:
a = torch.rand(2, 3)

a.add_(1)
a.mul_(2)
a.tanh_()


tensor([[0.9711, 0.9956, 0.9975],
        [0.9967, 0.9917, 0.9936]])

### Reduction Operations

In [10]:
a = torch.rand(2, 3)

print(a.sum())                # all elements
print(a.sum(dim=0))           # column-wise
print(a.sum(dim=1))           # row-wise

print(a.mean())               # global mean
print(a.mean(dim=0))          # column mean

print(a.std(dim=1))           # row std dev

print(a.min(), a.max())       # global min, max
print(a.min(dim=1))           # returns (values, indices)


tensor(3.4857)
tensor([1.4753, 0.8457, 1.1647])
tensor([2.3273, 1.1584])
tensor(0.5809)
tensor([0.7377, 0.4229, 0.5823])
tensor([0.2078, 0.4821])
tensor(0.0120) tensor(0.9484)
torch.return_types.min(
values=tensor([0.5451, 0.0120]),
indices=tensor([0, 1]))


### Matrix / Linear Algebra Ops

In [11]:
A = torch.rand(2, 3)
B = torch.rand(3, 4)

# Matrix multiplication
C = torch.matmul(A, B)
C = A @ B

# Transpose
print(A.t())         # swap last 2 dims

# Matrix determinant (square matrices)
M = torch.rand(3, 3)
print(torch.det(M))

# Matrix inverse
print(torch.inverse(M))


tensor([[0.8458, 0.3698],
        [0.9661, 0.7869],
        [0.5213, 0.0477]])
tensor(0.0048)
tensor([[  3.0583,  -9.7016,  23.2013],
        [  5.5415,  -7.3568,  11.0373],
        [ -8.0961,  16.4368, -26.6580]])


### Concatenation & Stacking

In [12]:
x = torch.rand(2, 3)
y = torch.rand(2, 3)

# Concatenate along rows (dim=0)
print(torch.cat((x, y), dim=0))

# Concatenate along columns (dim=1)
print(torch.cat((x, y), dim=1))

# Stack (creates new dimension)
print(torch.stack((x, y), dim=0))  # shape (2, 2, 3)


tensor([[0.2986, 0.4258, 0.3560],
        [0.3110, 0.1778, 0.4455],
        [0.8671, 0.2082, 0.1517],
        [0.3229, 0.7200, 0.1858]])
tensor([[0.2986, 0.4258, 0.3560, 0.8671, 0.2082, 0.1517],
        [0.3110, 0.1778, 0.4455, 0.3229, 0.7200, 0.1858]])
tensor([[[0.2986, 0.4258, 0.3560],
         [0.3110, 0.1778, 0.4455]],

        [[0.8671, 0.2082, 0.1517],
         [0.3229, 0.7200, 0.1858]]])


### Type Casting

In [13]:
a = torch.rand(3, 3)

print(a.float())
print(a.double())
print(a.int())
print(a.bool())


tensor([[0.1338, 0.8186, 0.8138],
        [0.2892, 0.6650, 0.3367],
        [0.6130, 0.3995, 0.5689]])
tensor([[0.1338, 0.8186, 0.8138],
        [0.2892, 0.6650, 0.3367],
        [0.6130, 0.3995, 0.5689]], dtype=torch.float64)
tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]], dtype=torch.int32)
tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])


### Device Movement (CPU/GPU)

In [ ]:
a = torch.rand(2, 3)

# Move to GPU
# a_gpu = a.to("cuda")

# Move back
# a_cpu = a_gpu.to("cpu")


In [27]:
from torch.autograd import Variable
import torch.nn as nn
import torch.nn.functional as F

## What is a *Variable* in PyTorch?

Before PyTorch 0.4, you had to wrap tensors in `Variable` to compute gradients:

```python
from torch.autograd import Variable
```

But **now `Tensor` itself acts like a Variable**.

👉 So in modern PyTorch:

**Every tensor with `requires_grad=True` is a Variable.**

Meaning:

* PyTorch starts tracking all operations done on the tensor
* It can compute gradients via backpropagation (`.backward()`)

---

## What is `requires_grad`?

`requires_grad=True` tells PyTorch:

> “Track everything done on this tensor so I can compute gradients later.”

Example:

In [28]:
x = torch.tensor(2.0, requires_grad=True)
y = x * 3
print(y)  # tensor(6., grad_fn=<MulBackward0>)

tensor(6., grad_fn=<MulBackward0>)


Notice the `grad_fn` — it means the tensor is part of a computation graph.

---

## What is a Gradient?

The **gradient** is the **derivative** of your output w.r.t your input.

👉 Used for training neural networks
👉 Used by optimizers like Adam, SGD
👉 Used for gradient descent to update weights

If `y = x * 3` then:

```
dy/dx = 3
```

We can see this using PyTorch:

In [29]:
x = torch.tensor(2.0, requires_grad=True)
y = x * 3

# Compute gradient
y.backward()

print(x.grad)   # tensor(3.)

tensor(3.)


✔ PyTorch automatically calculated dy/dx = 3

---

## Simple Example: y = x²

Mathematically:

```
y = x^2
dy/dx = 2x
```

Let’s check:

In [30]:
x = torch.tensor(4.0, requires_grad=True)
y = x ** 2

y.backward()
print(x.grad)   # tensor(8.)

tensor(8.)


✔ Correct → 2 × 4 = 8

---

## Multiple Operations Example

In [31]:
x = torch.tensor(3.0, requires_grad=True)

y = x * 2          # 6
z = y + 5          # 11
out = z ** 2       # 121

out.backward()
print(x.grad)

tensor(44.)


Math:

```
y = 2x
z = y + 5 = 2x + 5
out = (2x + 5)^2

d(out)/dx = 2(2x+5)*2 = 4(2x+5)
At x=3 → 4(11) = 44
```

PyTorch prints:

```
tensor(44.)
```

---

## Gradients only accumulate — they don’t reset automatically

In [32]:
x = torch.tensor(2.0, requires_grad=True)
y = x * 3
y.backward()
print(x.grad)   # 3

# Calling backward again without zeroing
y = x * 3
y.backward()
print(x.grad)   # now 6 (accumulated)

tensor(3.)
tensor(6.)


🔥 Always clear gradients before next backward:

In [33]:
x.grad.zero_()

tensor(0.)

## `torch.no_grad()` — turn off gradient tracking

Used during:

* inference
* evaluation
* updating tensors without tracking

Example:

In [34]:
x = torch.tensor(5.0, requires_grad=True)

with torch.no_grad():
    x += 3

print(x)         # tensor(8.)
print(x.requires_grad)    # True

tensor(8., requires_grad=True)
True


Even though `x` has requires_grad=True, the operation inside `no_grad()` does not track history.

---

## Example with a small “model weight”

Imagine a single weight **w**:

In [35]:
w = torch.tensor(1.0, requires_grad=True)

# simple prediction
y_pred = w * 5    # y = 5w

loss = (y_pred - 10)**2   # MSE loss

loss.backward()

print("Loss:", loss.item())
print("Gradient:", w.grad)  # tells us how to update w

Loss: 25.0
Gradient: tensor(-50.)


This is exactly what happens inside every neural network layer.

---

## Manual gradient descent (for beginners)

In [36]:
w = torch.tensor(1.0, requires_grad=True)

for i in range(5):
    y_pred = w * 5
    loss = (y_pred - 10)**2
    
    loss.backward()
    
    with torch.no_grad():
        w -= 0.1 * w.grad   # gradient descent update
    
    w.grad.zero_()
    
    print(i, w.item())

0 6.0
1 -14.0
2 66.0
3 -254.0
4 1026.0


This is the basic idea behind every optimizer like `SGD` or `Adam`.

---
`torch.no_grad()` is a **context manager** that tells PyTorch:

**“Disable gradient tracking inside this block.”**

---

### Why use `torch.no_grad()`?

Because PyTorch normally tracks **every operation** on tensors with `requires_grad=True` to build a computation graph for backpropagation.

But during:

* **inference / prediction**
* **evaluation**
* **updating values manually**
* **copying tensors**
* **freezing model parameters**

we **don’t want gradients** and **don’t want a computation graph**.

So we wrap code in:

```python
with torch.no_grad():
    # code here will NOT track gradients
```

---

### Simple Example

##### Without `no_grad()`

```python
import torch

x = torch.tensor(5.0, requires_grad=True)
y = x * 3
print(y.grad_fn)   # <MulBackward0>
```

🔹 PyTorch tracked the operation
🔹 A computation graph was created
🔹 Memory is used
🔹 Gradients will be computed during backward

---

##### With `torch.no_grad()`

```python
import torch

x = torch.tensor(5.0, requires_grad=True)

with torch.no_grad():
    y = x * 3

print(y.grad_fn)   # None
```

✔ No computation graph
✔ No gradient tracking
✔ Much less memory used
✔ Faster

---

### Why is it SUPER important?

##### 1. **Inference is faster**

No gradients → no graph building → lower memory & faster computation.

##### 2. **Prevents unwanted gradient updates**

When you update weights manually:

```python
with torch.no_grad():
    w -= lr * w.grad
```

This ensures PyTorch **does not track** this update as part of the graph.

##### 3. **Safe evaluation of validation data**

```python
model.eval()
with torch.no_grad():
    preds = model(X_val)
```

---

### One-line definition

**torch.no_grad() temporarily turns off autograd so operations inside it do not create gradients or computation graphs.**


---

### Summary (Very Simple)

| Concept                            | Meaning                                  |
| ---------------------------------- | ---------------------------------------- |
| **Tensor with requires_grad=True** | A variable whose gradient is tracked     |
| **grad**                           | Stores ∂output/∂input                    |
| **backward()**                     | Performs backpropagation                 |
| **grad_fn**                        | Shows which operation created the tensor |
| **no_grad()**                      | Turn off gradient tracking (inference)   |



### Simple Neural Network Training Step

- Initialize weights
- Compute forward pass
- Compute MSE loss
- Backpropagate using `.backward()`
- Manually update weights

In [37]:
# ----- 1. Create sample data -----
X = torch.tensor([[1.0], [2.0], [3.0], [4.0]])   # shape (4,1)
y = torch.tensor([[2.0], [4.0], [6.0], [8.0]])   # y = 2x

# ----- 2. Initialize weights -----
w1 = torch.randn(1, 4, requires_grad=True)   # first layer weights
b1 = torch.randn(4, requires_grad=True)

w2 = torch.randn(4, 1, requires_grad=True)   # second layer weights
b2 = torch.randn(1, requires_grad=True)

lr = 0.01     # learning rate
num_epochs = 5

# ----- 3. Training loop -----
for epoch in range(num_epochs):

    # ----- Forward Pass -----
    h = X @ w1 + b1        # Linear layer 1
    h_relu = torch.relu(h) # Activation
    y_pred = h_relu @ w2 + b2  # Linear layer 2

    # ----- Loss -----
    loss = torch.mean((y_pred - y)**2)

    # ----- Backward -----
    loss.backward()

    # ----- Update weights manually -----
    with torch.no_grad():
        w1 -= lr * w1.grad
        b1 -= lr * b1.grad
        w2 -= lr * w2.grad
        b2 -= lr * b2.grad

    # ----- Clear gradients -----
    w1.grad.zero_()
    b1.grad.zero_()
    w2.grad.zero_()
    b2.grad.zero_()

    if epoch % 10 == 0:
        print(f"Epoch {epoch}, Loss = {loss.item():.4f}")


Epoch 0, Loss = 20.6364


### Neural Network Using Optimizer (SGD)

In [38]:
# ----- 1. Sample Data -----
X = torch.tensor([[1.0], [2.0], [3.0], [4.0]])
y = torch.tensor([[2.0], [4.0], [6.0], [8.0]])

# ----- 2. Initialize weights -----
w1 = torch.randn(1, 4, requires_grad=True)
b1 = torch.randn(4, requires_grad=True)

w2 = torch.randn(4, 1, requires_grad=True)
b2 = torch.randn(1, requires_grad=True)

# Collect parameters for optimizer
params = [w1, b1, w2, b2]

# ----- 3. Optimizer (SGD) -----
optimizer = torch.optim.SGD(params, lr=0.01)

num_epochs = 5
# ----- 4. Training Loop -----
for epoch in range(num_epochs):

    # Forward
    h = X @ w1 + b1
    h_relu = torch.relu(h)
    y_pred = h_relu @ w2 + b2

    # Loss
    loss = torch.mean((y_pred - y)**2)

    # Backprop
    optimizer.zero_grad()   # clear old gradients
    loss.backward()         # compute new gradients
    optimizer.step()        # update weights

    if epoch % 10 == 0:
        print(f"Epoch {epoch}, Loss = {loss.item():.4f}")


Epoch 0, Loss = 0.4339


### What is `nn.Linear`?

`nn.Linear(in_features, out_features)` performs a **linear transformation**:

[
y = xW^{T} + b
]

* **W** → weight matrix of size `(out_features × in_features)`
* **b** → bias vector of size `(out_features)`

So if you call:

```python
layer = nn.Linear(3, 2)
```

Then:

* Input shape must be: `[batch_size, 3]`
* Output shape will be: `[batch_size, 2]`

PyTorch handles:
✔ Creating weights
✔ Creating bias
✔ Tracking gradients
✔ Updating parameters during training

---

### Example: Using `nn.Linear` in Functional Style

**No classes, everything step-by-step.**

We build a tiny model:

```
X → Linear(1→4) → ReLU → Linear(4→1) → Output
```

---

###**Code: Functional neural network using nn.Linear**





In [39]:
# ---------------------------
# 1. Data
# ---------------------------
X = torch.tensor([[1.0], [2.0], [3.0], [4.0]])   # Inputs
y = torch.tensor([[2.0], [4.0], [6.0], [8.0]])   # Targets (y = 2x)

# ---------------------------
# 2. Define layers (Functional Style)
# ---------------------------
layer1 = nn.Linear(1, 4)   # input 1 -> hidden 4
layer2 = nn.Linear(4, 1)   # hidden 4 -> output 1

# Optimizer
optimizer = torch.optim.SGD(list(layer1.parameters()) + 
                            list(layer2.parameters()), lr=0.01)

num_epochs = 5
# ---------------------------
# 3. Training Loop
# ---------------------------
for epoch in range(num_epochs):

    # ----- Forward Pass -----
    h = layer1(X)          # linear layer
    h = F.relu(h)          # activation
    y_pred = layer2(h)     # output layer

    # ----- Loss -----
    loss = F.mse_loss(y_pred, y)

    # ----- Backward Pass -----
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    if epoch % 10 == 0:
        print(f"Epoch {epoch}, Loss = {loss.item():.4f}")


Epoch 0, Loss = 40.9530


### What this example shows

##### ✔ Functional-style usage (no class)

You manually create each layer:

```python
layer1 = nn.Linear(1, 4)
layer2 = nn.Linear(4, 1)
```

##### ✔ Forward pass is explicit

```python
h = layer1(X)
h = F.relu(h)
y_pred = layer2(h)
```

##### ✔ Loss calculation

```python
loss = F.mse_loss(y_pred, y)
```

##### ✔ Backprop + update

```python
optimizer.zero_grad()
loss.backward()
optimizer.step()
```

Everything happens step-by-step so you can clearly see how the network works.

---

### Optional: Print weights and bias

```python
print(layer1.weight)
print(layer1.bias)
```

You'll see they update each epoch.

### What is `nn.Sequential`?

`nn.Sequential` lets you **stack layers in order** like this:

```python
model = nn.Sequential(
    nn.Linear(1, 4),
    nn.ReLU(),
    nn.Linear(4, 1)
)
```

It automatically connects output → next input → next output.

You only define the architecture once, and call:

```python
y_pred = model(X)
```

---

### Example: Neural Network with `nn.Sequential` (Functional Style)

We build:

```
X → Linear(1→4) → ReLU → Linear(4→1) → Output
```

---

### **Code**

In [40]:
# ---------------------------
# 1. Data
# ---------------------------
X = torch.tensor([[1.0], [2.0], [3.0], [4.0]])
y = torch.tensor([[2.0], [4.0], [6.0], [8.0]])   # y = 2x

# ---------------------------
# 2. Define model using nn.Sequential
# ---------------------------
model = nn.Sequential(
    nn.Linear(1, 4),   # layer 1
    nn.ReLU(),         # activation
    nn.Linear(4, 1)    # layer 2
)

# Optimizer
optimizer = torch.optim.SGD(model.parameters(), lr=0.01)

num_epochs = 5
# ---------------------------
# 3. Training Loop
# ---------------------------
for epoch in range(num_epochs):

    # Forward Pass
    y_pred = model(X)

    # Loss
    loss = F.mse_loss(y_pred, y)

    # Backward
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    if epoch % 10 == 0:
        print(f"Epoch {epoch}, Loss = {loss.item():.4f}")


Epoch 0, Loss = 34.9010



### Why `nn.Sequential` is helpful?

##### ✔ Cleaner model definition

No need to manually call each layer.

##### ✔ Easy to add/remove layers

Just modify the list.

##### ✔ Perfect for simple feedforward networks

Especially MLPs, CNN blocks, etc.

Example:

```python
model = nn.Sequential(
    nn.Linear(10, 32),
    nn.ReLU(),
    nn.Linear(32, 16),
    nn.ReLU(),
    nn.Linear(16, 1)
)
```


Below are **three clean, minimal, class-based PyTorch model examples**, one for each style:

1. **Very simple NN (fully manual forward calculations)**
2. **Class-based model using `nn.Linear` layers**
3. **Class-based model using `nn.Sequential`**

All examples include:

* A class defining the model
* A forward function
* Simple training loop template

This will give you a **clear understanding of how PyTorch models are structured under the hood**.

---

### **1. Class-Based Model: Very First Simple NN (Manual Weights)**

Here we **manually create weights and do matrix multiplications ourselves**.

##### 👉 Best for: understanding how PyTorch really works under the hood.


In [41]:
import torch
import torch.nn as nn
import torch.nn.functional as F

# ---------------------------------------------------
# 1. Simple model with manually created parameters
# ---------------------------------------------------
class SimpleManualNN(nn.Module):
    def __init__(self):
        super().__init__()

        # Manually define weights and biases
        self.w1 = nn.Parameter(torch.randn(1, 4))
        self.b1 = nn.Parameter(torch.randn(4))

        self.w2 = nn.Parameter(torch.randn(4, 1))
        self.b2 = nn.Parameter(torch.randn(1))

    def forward(self, x):
        h = x @ self.w1 + self.b1    # Linear layer 1
        h = F.relu(h)                # Activation
        out = h @ self.w2 + self.b2  # Linear layer 2
        return out


# Example usage
model = SimpleManualNN()
X = torch.tensor([[1.0], [2.0], [3.0], [4.0]])
y_pred = model(X)
print(y_pred)

tensor([[-1.3697],
        [-1.2692],
        [-1.1687],
        [-1.0682]], grad_fn=<AddBackward0>)


✔ Manually implemented linear layers
✔ Useful for learning core mechanics

---

### **2. Class-Based Model Using `nn.Linear` (Proper PyTorch Way)**

The cleanest and most common architecture structure.

In [42]:
import torch
import torch.nn as nn
import torch.nn.functional as F

# ---------------------------------------------------
# 2. Class model using nn.Linear layers
# ---------------------------------------------------
class LinearNN(nn.Module):
    def __init__(self):
        super().__init__()
        self.fc1 = nn.Linear(1, 4)   # input → hidden
        self.fc2 = nn.Linear(4, 1)   # hidden → output

    def forward(self, x):
        x = F.relu(self.fc1(x))
        x = self.fc2(x)
        return x


# Example usage
model = LinearNN()
X = torch.tensor([[1.0], [2.0], [3.0], [4.0]])
y_pred = model(X)
print(y_pred)

tensor([[-0.4084],
        [-0.4179],
        [-0.4242],
        [-0.4304]], grad_fn=<AddmmBackward0>)


✔ Clean and flexible
✔ Easy to expand with more layers

---

### **3. Class-Based Model Using `nn.Sequential`**

Here, the entire network is wrapped inside one Sequential block.

In [43]:
import torch
import torch.nn as nn
import torch.nn.functional as F

# ---------------------------------------------------
# 3. Class model using nn.Sequential
# ---------------------------------------------------
class SequentialNN(nn.Module):
    def __init__(self):
        super().__init__()
        self.model = nn.Sequential(
            nn.Linear(1, 4),
            nn.ReLU(),
            nn.Linear(4, 1)
        )

    def forward(self, x):
        return self.model(x)


# Example usage
model = SequentialNN()
X = torch.tensor([[1.0], [2.0], [3.0], [4.0]])
y_pred = model(X)
print(y_pred)

tensor([[-0.0651],
        [ 0.0861],
        [ 0.1873],
        [ 0.2884]], grad_fn=<AddmmBackward0>)


✔ Very compact
✔ Perfect for simple feedforward architectures

---

### **Training Loop Template (Works for All 3 Models)**

In [44]:
X = torch.tensor([[1.0], [2.0], [3.0], [4.0]])
y = torch.tensor([[2.0], [4.0], [6.0], [8.0]])

model = LinearNN()        # or SimpleManualNN(), SequentialNN()
optimizer = torch.optim.SGD(model.parameters(), lr=0.01)
loss_fn = nn.MSELoss()

num_epochs = 5
# ---------------------------
# Training Loop
for epoch in range(num_epochs):
    optimizer.zero_grad()

    y_pred = model(X)
    loss = loss_fn(y_pred, y)

    loss.backward()
    optimizer.step()

    if epoch % 10 == 0:
        print(f"Epoch {epoch} Loss: {loss.item():.4f}")

Epoch 0 Loss: 29.9272


### Summary Table (Easy Understanding)

| Model Type         | How It's Built                                  | Best For                          |
| ------------------ | ----------------------------------------------- | --------------------------------- |
| **SimpleManualNN** | Manual weights (`nn.Parameter`) + manual matmul | Understanding internals           |
| **LinearNN**       | Uses `nn.Linear` layers                         | Standard choice for most networks |
| **SequentialNN**   | Uses `nn.Sequential` container                  | Very compact CNN/MLP blocks       |
