In [1]:
import torch
import numpy as np

In [3]:
arr = np.array([1, 2, 3])

tensor = torch.tensor(arr)

print(tensor)

tensor([1, 2, 3], dtype=torch.int32)


In [5]:
arr = np.array([[1, 2, 3],[4,5,6]])

tensor = torch.tensor(arr)

print(tensor)

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)


In [8]:
tensor = torch.zeros((3,4))
print(tensor)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [9]:
tensor = torch.ones((3,4))
print(tensor)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [12]:
# default dtype is float32
tensor = torch.zeros((3,4),dtype=torch.float16)
print(tensor, tensor.dtype)

# we can also manually set the dtype
tensor = torch.zeros((3,4), dtype=torch.float16)
print(tensor)
tensor = torch.ones((3,4), dtype=torch.int32)
print(tensor)
tensor = torch.rand((3,4), dtype = torch.double)
print(tensor)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]], dtype=torch.float16) torch.float16
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]], dtype=torch.float16)
tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]], dtype=torch.int32)
tensor([[0.7107, 0.0360, 0.3087, 0.6320],
        [0.2307, 0.2003, 0.3482, 0.3054],
        [0.2887, 0.3139, 0.0932, 0.6823]], dtype=torch.float64)
